# Generated by Django 2.0 on 2018-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180210_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='1123', max_length=100),
            preserve_default=False,
        ),
    ]
