# Generated by Django 2.0 on 2018-02-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0002_auto_20180210_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landing.Post')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
            bases=('landing.post',),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='job_type',
            field=models.ForeignKey(on_delete='CASCADE', to='ads.Type'),
        ),
        migrations.AddField(
            model_name='ad',
            name='sponsor',
            field=models.ForeignKey(on_delete='CASCADE', to='ads.Sponsor'),
        ),
    ]
