# Generated by Django 2.0 on 2018-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
