# Generated by Django 2.0 on 2018-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
