# Generated by Django 2.0 on 2018-02-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20180210_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='image_url',
        ),
    ]
