# Generated by Django 2.0 on 2018-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20180210_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
